repos:
  - repo: local
    hooks:
      - id: black
        language: python
        name: black
        pass_filenames: false
        language_version: python3.8
        entry: poetry run black fastapi_filters tests examples

  - repo: local
    hooks:
      - id: ruff
        language: python
        name: ruff
        pass_filenames: false
        language_version: python3.8
        entry: poetry run ruff check --fix --exit-non-zero-on-fix --show-fixes fastapi_filters tests examples

  - repo: local
    hooks:
      - id: mypy
        language: python
        name: mypy
        pass_filenames: false
        entry: poetry run mypy fastapi_filters examples --show-error-codes
